Add support for creation of record links
surrealdb/surrealdb.py pull request #31
Opened 2022-10-17 21:13 UTC by HakierGrzonzo

# Problem:

Currently surrealdb does not allow the creation of record links when creating, upserting or replacing records. This is caused by the use of simple json parsers that do not handle record links.

# Solution:

A new encoder, that encodes objects to valid surreal queries instead of json.

If a nested object has a `id` key or attribute, it will be encoded as a *record link*.

2022-10-17 21:19 UTC, tsunyoku requested changes
I understand the aims of this PR, but the approach is quite naive. This is making many assumptions regarding the input, and I'm fearful that accepting this will lead to many difficult-to-track bugs.

2022-10-18 17:17 UTC, HakierGrzonzo commented
I changed the proposed behavior so instead of automatically inserting ids as links, a special object is required, making the request to create the link explicit.

The only issue in this version I can see is the lack of checking for record links in object properties.

2022-10-18 17:23 UTC, tsunyoku reviewed
I'd really prefer to not be writing our own dumping logic, there's not really any reason not to feed it to jsonlib. I agree the RecordLink class is a better approach, but I do feel if we can keep to using jsonlib that would be good. These string joins, reprs etc. make me feel extremely cautious of bugs.

2022-10-18 17:25 UTC, HakierGrzonzo commented
> I'd really prefer to not be writing our own dumping logic, there's not really any reason not to feed it to jsonlib. I agree the RecordLink class is a better approach, but I do feel if we can keep to using jsonlib that would be good. These string joins, reprs etc. make me feel extremely cautious of bugs.

Yes, such approach is not ideal, but sice surreal.db has its own format for data, it is necessary.

I could write some tests for the parser, which currently falls back on the jsonlib when necessary.

2022-10-18 17:32 UTC, tsunyoku commented
> Yes, such approach is not ideal, but sice surreal.db has its own format for data, it is necessary.

Would you not agree it is better for people to manually write their queries in the cases they are more complex? Record links are cool, but given their syntax I think people are better off using the general query function than using these helper ones because we don't really have an ideal way of dealing with this correctly; if we had some form of ORM I think this wouldn't be an issue, I just feel pretty stubbornly against this kind of serialization by ourselves.

Tests would be helpful for sure, I just don't know how much of a good idea this approach is.

2022-10-18 17:37 UTC, HakierGrzonzo commented
> if we had some form of ORM

I am currently working on one based on `pydantic`. As a result I will try to work around the issue and try to handle record links there.

If you want to follow its development you can do so here: https://github.com/HakierGrzonzo/Kronikarz/tree/2-skonfigurowanie-fastapi_users/backend/app/surreal_orm

Thanks for your time.

2022-10-18 17:37 UTC, closed without merging