Fix websocket exception handling
surrealdb/surrealdb.py pull request #33
Opened 2022-10-23 21:32 UTC by HakierGrzonzo

When `surrealdb` would return an error, the exception would get raised in the scope of the connection handler.

This fix causes the exception to be passed to the future, so it can be handled by the user.

2022-10-24 00:30 UTC, tsunyoku requested changes

2022-10-24 00:30 UTC, tsunyoku commented on surrealdb/clients/ws.py
>              if request_future is not None:
you added a check above that this isn’t None, so you should remove this now unnecessary if check. otherwise, looks good!

2022-10-25 08:35 UTC, tsunyoku approved these changes

2022-10-25 08:38 UTC, jyooru approved these changes

2022-10-25 18:35 UTC, merged